
    drop table if exists drivers cascade;
    drop table if exists orders cascade ;
    drop table if exists vehicles cascade;


    create table drivers (
        id bigint generated by default as identity,
        address varchar(255),
        cellphone varchar(255) not null,
        identification varchar(255) not null,
        last_name varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table orders (
        driver_id bigint,
        id bigint generated by default as identity,
        address varchar(255) not null,
        order_type varchar(255),
        primary key (id)
    );

    create table vehicles (
        driver_id bigint,
        id bigint generated by default as identity,
        capacity varchar(255),
        model varchar(255) not null,
        plate_vehicle varchar(255) not null,
        primary key (id)
    );

    alter table if exists orders
       add constraint FKqohd0dujmkcb12rcjy4b1fj4u
       foreign key (driver_id)
       references drivers;

    alter table if exists vehicles
       add constraint FKaashphrwfd4ts511y8vj785ia
       foreign key (driver_id)
       references drivers;